# This property reduces the amount of memory (RAM) that the Gradle build
# system uses. It helps prevent "Could not reserve enough space" errors on
# systems with limited memory by lowering the heap size from 1.5GB to 1GB.
org.gradle.jvmargs=-Xmx1024m
